### ISSUE TITLE
go 1.20

### ISSUE THREAD

**Issue by Phuong39** [quic-go/quic-go#3907]
i run example on go 1.20 and got error:

```
# github.com/quic-go/quic-go/internal/qtls
D:\gopath\src\github.com\quic-go\quic-go\internal\qtls\go120.go:18:15: undefined: qtls.Alert
D:\gopath\src\github.com\quic-go\quic-go\internal\qtls\go120.go:24:26: undefined: qtls.CipherSuiteTLS13
D:\gopath\src\github.com\quic-go\quic-go\internal\qtls\go120.go:36:25: undefined: qtls.ConnectionStateWith0RTT
D:\gopath\src\github.com\quic-go\quic-go\internal\qtls\go120.go:38:25: undefined: qtls.EncryptionLevel
D:\gopath\src\github.com\quic-go\quic-go\internal\qtls\go120.go:40:19: undefined: qtls.Extension
D:\gopath\src\github.com\quic-go\quic-go\internal\qtls\go120.go:44:21: undefined: qtls.RecordLayer
D:\gopath\src\github.com\quic-go\quic-go\internal\qtls\go120.go:49:29: undefined: qtls.EncryptionHandshake
D:\gopath\src\github.com\quic-go\quic-go\internal\qtls\go120.go:51:24: undefined: qtls.Encryption0RTT
D:\gopath\src\github.com\quic-go\quic-go\internal\qtls\go120.go:53:31: undefined: qtls.EncryptionApplication
D:\gopath\src\github.com\quic-go\quic-go\internal\qtls\go120.go:58:14: undefined: qtls.AEADAESGCMTLS13
D:\gopath\src\github.com\quic-go\quic-go\internal\qtls\go120.go:58:14: too many errors
```

how fix it ? 

my code :
```
package main

import (
	"bufio"
	"bytes"
	"context"
	"crypto/tls"
	"crypto/x509"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"sync"

	"github.com/quic-go/quic-go"
	"github.com/quic-go/quic-go/http3"
	"github.com/quic-go/quic-go/internal/testdata"
	"github.com/quic-go/quic-go/internal/utils"
	"github.com/quic-go/quic-go/logging"
	"github.com/quic-go/quic-go/qlog"
)

func main() {
	verbose := flag.Bool("v", false, "verbose")
	quiet := flag.Bool("q", false, "don't print the data")
	keyLogFile := flag.String("keylog", "", "key log file")
	insecure := flag.Bool("insecure", false, "skip certificate verification")
	enableQlog := flag.Bool("qlog", false, "output a qlog (in the same directory)")
	flag.Parse()
	urls := flag.Args()

	logger := utils.DefaultLogger

	if *verbose {
		logger.SetLogLevel(utils.LogLevelDebug)
	} else {
		logger.SetLogLevel(utils.LogLevelInfo)
	}
	logger.SetLogTimeFormat("")

	var keyLog io.Writer
	if len(*keyLogFile) > 0 {
		f, err := os.Create(*keyLogFile)
		if err != nil {
			log.Fatal(err)
		}
		defer f.Close()
		keyLog = f
	}

	pool, err := x509.SystemCertPool()
	if err != nil {
		log.Fatal(err)
	}
	testdata.AddRootCA(pool)

	var qconf quic.Config
	if *enableQlog {
		qconf.Tracer = func(ctx context.Context, p logging.Perspective, connID quic.ConnectionID) logging.ConnectionTracer {
			filename := fmt.Sprintf("client_%x.qlog", connID)
			f, err := os.Create(filename)
			if err != nil {
				log.Fatal(err)
			}
			log.Printf("Creating qlog file %s.\n", filename)
			return qlog.NewConnectionTracer(utils.NewBufferedWriteCloser(bufio.NewWriter(f), f), p, connID)
		}
	}
	roundTripper := &http3.RoundTripper{
		TLSClientConfig: &tls.Config{
			RootCAs:            pool,
			InsecureSkipVerify: *insecure,
			KeyLogWriter:       keyLog,
		},
		QuicConfig: &qconf,
	}
	defer roundTripper.Close()
	hclient := &http.Client{
		Transport: roundTripper,
	}

	var wg sync.WaitGroup
	wg.Add(len(urls))
	for _, addr := range urls {
		logger.Infof("GET %s", addr)
		go func(addr string) {
			rsp, err := hclient.Get(addr)
			if err != nil {
				log.Fatal(err)
			}
			logger.Infof("Got response for %s: %#v", addr, rsp)

			body := &bytes.Buffer{}
			_, err = io.Copy(body, rsp.Body)
			if err != nil {
				log.Fatal(err)
			}
			if *quiet {
				logger.Infof("Response Body: %d bytes", body.Len())
			} else {
				logger.Infof("Response Body:")
				logger.Infof("%s", body.Bytes())
			}
			wg.Done()
		}(addr)
	}
	wg.Wait()
}
```

**Comment by marten-seemann** [comment]
No idea, it works fine with Go 1.20 on my machine and on CI.

**Comment by gaby** [comment]
@marten-seemann I'm having the same issue as @Phuong39, I don't even use quic-go directly. It's an indirect dependency.

```
# github.com/quic-go/quic-go/internal/qtls
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:18:15: undefined: qtls.Alert
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:24:26: undefined: qtls.CipherSuiteTLS13
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:36:25: undefined: qtls.ConnectionStateWith0RTT
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:38:25: undefined: qtls.EncryptionLevel
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:40:19: undefined: qtls.Extension
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:44:21: undefined: qtls.RecordLayer
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:49:29: undefined: qtls.EncryptionHandshake
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:51:24: undefined: qtls.Encryption0RTT
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:53:31: undefined: qtls.EncryptionApplication
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:58:14: undefined: qtls.AEADAESGCMTLS13
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:58:14: too many errors
```

**Comment by gaby** [comment]
Running `govulncheck` results in this:

```console
$ govulncheck ./...
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Using go1.20.5 and govulncheck@v0.0.0 with
vulnerability data from https://vuln.go.dev (last modified 2023-06-22 16:44:55 +0000 UTC).

There are errors with the provided package patterns:

/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:18:15: undefined: qtls.Alert
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:24:26: undefined: qtls.CipherSuiteTLS13
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:36:25: undefined: qtls.ConnectionStateWith0RTT
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:38:25: undefined: qtls.EncryptionLevel
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:40:19: undefined: qtls.Extension
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:44:21: undefined: qtls.RecordLayer
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:49:29: undefined: qtls.EncryptionHandshake
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:51:24: undefined: qtls.Encryption0RTT
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:53:31: undefined: qtls.EncryptionApplication
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:58:14: undefined: qtls.AEADAESGCMTLS13
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:63:35: too many arguments in call to qtls.Client
	have (net.Conn, *tls.Config, *"github.com/quic-go/qtls-go1-20".ExtraConfig)
	want (net.Conn, *tls.Config)
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:68:35: too many arguments in call to qtls.Server
	have (net.Conn, *tls.Config, *"github.com/quic-go/qtls-go1-20".ExtraConfig)
	want (net.Conn, *tls.Config)
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:72:14: conn.ConnectionStateWith0RTT undefined (type *"github.com/quic-go/qtls-go1-20".Conn has no field or method ConnectionStateWith0RTT)
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:94:15: undefined: qtls.CipherSuiteTLS13
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/handshake/aead.go:19:31: suite.Hash undefined (type *invalid type has no field or method Hash)
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/handshake/crypto_setup.go:484:17: h.extraConf.MaxEarlyData undefined (type *"github.com/quic-go/qtls-go1-20".ExtraConfig has no field or method MaxEarlyData)
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/handshake/crypto_setup.go:490:16: h.conn.GetSessionTicket undefined (type *"github.com/quic-go/qtls-go1-20".Conn has no field or method GetSessionTicket)
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/handshake/crypto_setup.go:276:3: unknown field GetExtensions in struct literal of type "github.com/quic-go/qtls-go1-20".ExtraConfig
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/handshake/crypto_setup.go:277:3: unknown field ReceivedExtensions in struct literal of type "github.com/quic-go/qtls-go1-20".ExtraConfig
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/handshake/crypto_setup.go:278:3: unknown field AlternativeRecordLayer in struct literal of type "github.com/quic-go/qtls-go1-20".ExtraConfig
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/handshake/crypto_setup.go:279:3: unknown field EnforceNextProtoSelection in struct literal of type "github.com/quic-go/qtls-go1-20".ExtraConfig
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/handshake/crypto_setup.go:280:3: unknown field MaxEarlyData in struct literal of type "github.com/quic-go/qtls-go1-20".ExtraConfig
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/handshake/crypto_setup.go:282:3: unknown field Rejected0RTT in struct literal of type "github.com/quic-go/qtls-go1-20".ExtraConfig
/home/ubuntu/go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/handshake/crypto_setup.go:550:19: h.conn.HandlePostHandshakeMessage undefined (type *"github.com/quic-go/qtls-go1-20".Conn has no field or method HandlePostHandshakeMessage)
```

**Comment by gaby** [comment]
Running `staticcheck`:

```console
$ staticcheck ./...
-: # github.com/quic-go/quic-go/internal/qtls
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:18:15: undefined: qtls.Alert
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:24:26: undefined: qtls.CipherSuiteTLS13
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:36:25: undefined: qtls.ConnectionStateWith0RTT
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:38:25: undefined: qtls.EncryptionLevel
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:40:19: undefined: qtls.Extension
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:44:21: undefined: qtls.RecordLayer
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:49:29: undefined: qtls.EncryptionHandshake
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:51:24: undefined: qtls.Encryption0RTT
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:53:31: undefined: qtls.EncryptionApplication
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:58:14: undefined: qtls.AEADAESGCMTLS13
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:58:14: too many errors (compile)
```

Running `go vet`

```console
go vet ./...
# github.com/quic-go/quic-go/internal/qtls
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:18:15: undefined: qtls.Alert
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:24:26: undefined: qtls.CipherSuiteTLS13
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:36:25: undefined: qtls.ConnectionStateWith0RTT
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:38:25: undefined: qtls.EncryptionLevel
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:40:19: undefined: qtls.Extension
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:44:21: undefined: qtls.RecordLayer
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:49:29: undefined: qtls.EncryptionHandshake
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:51:24: undefined: qtls.Encryption0RTT
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:53:31: undefined: qtls.EncryptionApplication
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:58:14: undefined: qtls.AEADAESGCMTLS13
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:58:14: too many errors

```

**Comment by theraphim** [comment]
Had the same problem here. go get -u -v ./... pulls in go-1-20 v.0.3.0, which doesn't have these symbols. Manually pulling v0.2.2 fixes the build.

> [stingray@evac]~/m/muxproxy% go get github.com/quic-go/qtls-go1-20@v0.2.2
> go: downloading github.com/quic-go/qtls-go1-20 v0.2.2
> go: downgraded github.com/quic-go/qtls-go1-20 v0.3.0 => v0.2.2

**Comment by gaby** [comment]
> Had the same problem here. go get -u -v ./... pulls in go-1-20 v.0.3.0, which doesn't have these symbols. Manually pulling v0.2.2 fixes the build.
> 
> > [stingray@evac]~/m/muxproxy% go get github.com/quic-go/qtls-go1-20@v0.2.2
> > go: downloading github.com/quic-go/qtls-go1-20 v0.2.2
> > go: downgraded github.com/quic-go/qtls-go1-20 v0.3.0 => v0.2.2

Ohhhh, looking at the repo. I dont even see v0.3.0

**Comment by theraphim** [comment]
Look no further than https://github.com/quic-go/qtls-go1-20/tags :)

**Comment by gaby** [comment]
> Look no further than https://github.com/quic-go/qtls-go1-20/tags :)

Thanks, i was looking in the releases page only :-)

**Comment by gaby** [comment]
@theraphim My main problem is that my code doesn't use this library, it's a dependency that's using it... So when I downgrade qtls-go to v0.2.2, now I get errors in a different library

**Comment by theraphim** [comment]
@gaby let's hope @marten-seemann will notice our conversation and will fix it :)

**Comment by marten-seemann** [comment]
There’s never, ever, ever a reason to update qtls independently of quic-go. 

If you do a breaking version upgrade, your build might break. The solution is simple: don’t do that.

**Comment by gaby** [comment]
> There’s never, ever, ever a reason to update qtls independently of quic-go.
> 
> If you do a breaking version upgrade, your build might break. The solution is simple: don’t do that.

I was able to fix it by removing all the dependencies and running `go mod tidy`. Thanks for your help

**Comment by iwind** [comment]
The related projects in the same organization SHOULD BE compatible, or you should mark the issue in the README, and should not close the issue roughly.

**Comment by marten-seemann** [comment]
@iwind, no this is just plainly wrong.

The `go.mod` file specifies which versions quic-go v0.36.1 imports. If you go and modify these versions, to the point where you upgrade dependencies, this is your fault. You can't expect _every_ version of quic-go to work with _every_ random version of qtls.

**Comment by chaosmatrix** [comment]
(v0.36.1) Same problem and fix by downgrade into `github.com/quic-go/qtls-go1-20 v0.2.2`.

When people who used `go get -u` to update the exist project, all modules in `go.mod` will be updated into latest version.
But the latest version of `github.com/quic-go/quic-go` is not compatible with `github.com/quic-go/qtls-go1-20`, so the error has occurred.

To help people to prevent this kind of mistake, the easy way is making the latest version of `quic-go` and `qtls-go1-20` / `qtls-go1-19` are compatible with each other.
